# Crawling

In [5]:
pip install requests beautifulsoup4

Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2024.12.14)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Note: you may need to restart the kernel to use updated packages.

In [107]:
from bs4 import BeautifulSoup
import requests
url="https://arxiv.org/list/cs.GT/recent"
res=requests.get(url)
#res.encoding="utf-8"
print(res)
print(res.encoding)

<Response [200]>
utf-8

In [109]:
if res.status_code==200:
    print("Url is Connected")
elif res.status_code==404:
    print("Page not Found")
else:
    print("Url is Disconnected")

Url is Connected

In [111]:
soup = BeautifulSoup(res.text, "html.parser")
print(soup)

<!DOCTYPE html>

<html lang="en">
<head> <title>Computer Science and Game Theory  </title>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<link href="/static/browse/0.3.4/images/icons/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/static/browse/0.3.4/images/icons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/static/browse/0.3.4/images/icons/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/static/browse/0.3.4/images/icons/site.webmanifest" rel="manifest"/>
<link color="#5bbad5" href="/static/browse/0.3.4/images/icons/safari-pinned-tab.svg" rel="mask-icon"/>
<meta content="#da532c" name="msapplication-TileColor"/>
<meta content="#ffffff" name="theme-color"/>
<link href="/static/browse/0.3.4/css/arXiv.css?v=20241206" media="screen" rel="stylesheet" type="text/css">
<link href="/static/browse/0.3.4/css/arXiv-print.css?v=20200611" media="print" rel="stylesheet" type="text/css">
<link href="/static/browse/0.3.4/css/browse_search.css" media="screen" rel="stylesheet" type="text/css">
<script language="javascript" src="/static/browse/0.3.4/js/accordion.js"></script>
<script language="javascript" src="/static/browse/0.3.4/js/optin-modal.js?v=20250819"></script>
<script src="/static/browse/0.3.4/js/mathjaxToggle.min.js" type="text/javascript"></script>
<script language="javascript" type="text/javascript">mathjaxToggle();</script>
</link></link></link></head>
<body class="with-cu-identity">
<div class="flex-wrap-footer">
<header>
<a class="is-sr-only" href="#content">Skip to main content</a>
<!-- start desktop header -->
<div class="columns is-vcentered is-hidden-mobile" id="cu-identity">
<div class="column" id="cu-logo">
<a href="https://www.cornell.edu/"><img alt="Cornell University" src="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg"/></a>
</div><!-- /from April 7 at 1:00 AM to May 29 at 21:40 --><!-- /from May 2 at 1:00 AM to May 5 at 9:45 AM --><div class="column" id="support-ack">
<span id="support-ack-url">We gratefully acknowledge support from the Simons Foundation, <a href="https://info.arxiv.org/about/ourmembers.html">member institutions</a>, and all contributors.</span>
<a class="btn-header-donate" href="https://info.arxiv.org/about/donate.html">Donate</a>
</div>
</div>
<div class="is-hidden-mobile" id="header">
<a aria-hidden="true" href="/IgnoreMe" tabindex="-1"></a>
<div class="header-breadcrumbs">
<a href="/"><img alt="arxiv logo" src="/static/browse/0.3.4/images/arxiv-logo-one-color-white.svg" style="height:40px;"/></a> <span>&gt;</span>
<a href="/list/cs.GT/recent">cs.GT</a>
</div>
<div class="columns is-vcentered is-mobile" style="justify-content: flex-end;">
</div>
<div class="search-block level-right">
<form action="https://arxiv.org/search" class="level-item mini-search" method="GET">
<div class="field has-addons">
<div class="control">
<input aria-label="Search term or terms" class="input is-small" name="query" placeholder="Search..." type="text"/>
<p class="help"><a href="https://info.arxiv.org/help">Help</a> | <a href="https://arxiv.org/search/advanced">Advanced Search</a></p>
</div>
<div class="control">
<div class="select is-small">
<select aria-label="Field to search" name="searchtype">
<option selected="selected" value="all">All fields</option>
<option value="title">Title</option>
<option value="author">Author</option>
<option value="abstract">Abstract</option>
<option value="comments">Comments</option>
<option value="journal_ref">Journal reference</option>
<option value="acm_class">ACM classification</option>
<option value="msc_class">MSC classification</option>
<option value="report_num">Report number</option>
<option value="paper_id">arXiv identifier</option>
<option value="doi">DOI</option>
<option value="orcid">ORCID</option>
<option value="author_id">arXiv author ID</option>
<option value="help">Help pages</option>
<option value="full_text">Full text</option>
</select>
</div>
</div>
<input name="source" type="hidden" value="header"/>
<button class="button is-small is-cul-darker">Search</button>
</div>
</form>
</div>
</div><!-- /end desktop header -->
<div class="mobile-header">
<div class="columns is-mobile">
<div class="column logo-arxiv"><a href="https://arxiv.org/"><img alt="arXiv logo" src="/static/browse/0.3.4/images/arxiv-logomark-small-white.svg" style="height:60px;"/></a></div>
<div class="column logo-cornell"><a href="https://www.cornell.edu/">
<picture>
<source media="(min-width: 501px)" sizes="400w" srcset="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg  400w"/>
<source srcset="/static/browse/0.3.4/images/icons/cu/cornell_seal_simple_black.svg 2x"/>
<img alt="Cornell University Logo" src="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg"/>
</picture>
</a></div>
<div class="column nav" id="toggle-container" role="menubar">
<button class="toggle-control"><svg class="icon filter-white" viewbox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><title>open search</title><path d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path></svg></button>
<div class="mobile-toggle-block toggle-target">
<form action="https://arxiv.org/search" class="mobile-search-form" method="GET">
<div class="field has-addons">
<input aria-label="Search term or terms" class="input" name="query" placeholder="Search..." type="text">
<input name="source" type="hidden" value="header"/>
<input name="searchtype" type="hidden" value="all"/>
<button class="button">GO</button>
</input></div>
</form>
</div>
<button class="toggle-control"><svg class="icon filter-white" role="menu" viewbox="0 0 448 512" xmlns="http://www.w3.org/2000/svg"><title>open navigation menu</title><path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg></button>
<div class="mobile-toggle-block toggle-target">
<nav aria-labelledby="mobilemenulabel" class="mobile-menu">
<h2 id="mobilemenulabel">quick links</h2>
<ul>
<li><a href="https://arxiv.org/login">Login</a></li>
<li><a href="https://info.arxiv.org/help">Help Pages</a></li>
<li><a href="https://info.arxiv.org/about">About</a></li>
</ul>
</nav>
</div>
</div>
</div>
</div><!-- /end mobile-header -->
</header>
<main>
<div id="content">
<div id="content-inner">
<div id="dlpage">
<h1>Computer Science and Game Theory</h1>
<h2>Authors and titles for recent submissions</h2>
<ul>
<li>
<a href="/list/cs.GT/recent?skip=0&amp;show=50">
          Tue, 17 Feb 2026
        </a>
</li><li>
<a href="/list/cs.GT/recent?skip=25&amp;show=50">
          Mon, 16 Feb 2026
        </a>
</li><li>
<a href="/list/cs.GT/recent?skip=38&amp;show=50">
          Fri, 13 Feb 2026
        </a>
</li><li>
<a href="/list/cs.GT/recent?skip=61&amp;show=50">
          Thu, 12 Feb 2026
        </a>
</li><li>
<a href="/list/cs.GT/recent?skip=74&amp;show=50">
          Wed, 11 Feb 2026
        </a>
</li></ul>
<p>See today's <a aria-labelledby="new-cs.GT" href="/list/cs.GT/new" id="new-cs.GT">new</a> changes</p>
<div class="paging">Total of 82 entries :      <span>1-50</span>
<a href="/list/cs.GT/recent?skip=50&amp;show=50">51-82</a>
</div>
<div class="morefewer">Showing up to 50 entries per page:
          <a href="/list/cs.GT/recent?skip=0&amp;show=25" rel="nofollow">
      fewer</a>
 |
          <span style="color: #454545">more</span>
 |
          <a href="/list/cs.GT/recent?skip=0&amp;show=2000" rel="nofollow">
      all</a>
</div>
<dl id="articles">
<h3>Tue, 17 Feb 2026 (showing 25 of 25 entries )</h3>
<dt>
<a name="item1">[1]</a>
<a href="/abs/2602.14966" id="2602.14966" title="Abstract">
        arXiv:2602.14966
      </a>

        [<a aria-labelledby="pdf-2602.14966" href="/pdf/2602.14966" id="pdf-2602.14966" title="Download PDF">pdf</a>, <a aria-labelledby="html-2602.14966" href="https://arxiv.org/html/2602.14966v1" id="html-2602.14966" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>, <a aria-labelledby="oth-2602.14966" href="/format/2602.14966" id="oth-2602.14966" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          Robust Value Maximization in Challenge the Champ Tournaments with Probabilistic Outcomes
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Bhaskar,+U">Umang Bhaskar</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Chaudhary,+J">Juhi Chaudhary</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Gupta,+S">Sushmita Gupta</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Jain,+P">Pallavi Jain</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Seetharaman,+S">Sanjay Seetharaman</a></div>
<div class="list-comments mathjax"><span class="descriptor">Comments:</span>
          28 pages; full version of the paper to appear in AAMAS 2026
        </div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>; Data Structures and Algorithms (cs.DS)
        </div>
</div>
</dd>
<dt>
<a name="item2">[2]</a>
<a href="/abs/2602.14961" id="2602.14961" title="Abstract">
        arXiv:2602.14961
      </a>

        [<a aria-labelledby="pdf-2602.14961" href="/pdf/2602.14961" id="pdf-2602.14961" title="Download PDF">pdf</a>, <a aria-labelledby="html-2602.14961" href="https://arxiv.org/html/2602.14961v1" id="html-2602.14961" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>, <a aria-labelledby="oth-2602.14961" href="/format/2602.14961" id="oth-2602.14961" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          The Distortion of Stable Matching
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Filos-Ratsikas,+A">Aris Filos-Ratsikas</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kalantzis,+G">Georgios Kalantzis</a></div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>
</div>
</div>
</dd>
<dt>
<a name="item3">[3]</a>
<a href="/abs/2602.14858" id="2602.14858" title="Abstract">
        arXiv:2602.14858
      </a>

        [<a aria-labelledby="pdf-2602.14858" href="/pdf/2602.14858" id="pdf-2602.14858" title="Download PDF">pdf</a>, <a aria-labelledby="html-2602.14858" href="https://arxiv.org/html/2602.14858v1" id="html-2602.14858" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>, <a aria-labelledby="oth-2602.14858" href="/format/2602.14858" id="oth-2602.14858" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          Thermal Min-Max Games: Unifying Bounded Rationality and Typical-Case Equilibrium
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ichikawa,+Y">Yuma Ichikawa</a></div>
<div class="list-comments mathjax"><span class="descriptor">Comments:</span>
          31 pages, 4 figures
        </div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>; Disordered Systems and Neural Networks (cond-mat.dis-nn)
        </div>
</div>
</dd>
<dt>
<a name="item4">[4]</a>
<a href="/abs/2602.14850" id="2602.14850" title="Abstract">
        arXiv:2602.14850
      </a>

        [<a aria-labelledby="pdf-2602.14850" href="/pdf/2602.14850" id="pdf-2602.14850" title="Download PDF">pdf</a>, <a aria-labelledby="html-2602.14850" href="https://arxiv.org/html/2602.14850v1" id="html-2602.14850" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>, <a aria-labelledby="oth-2602.14850" href="/format/2602.14850" id="oth-2602.14850" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          Fair Allocation with Initial Utilities
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Boehmer,+N">Niclas Boehmer</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kreisel,+L">Luca Kreisel</a></div>
<div class="list-comments mathjax"><span class="descriptor">Comments:</span>
          34 pages. An extended abstract is scheduled to appear in the proceedings of the 25th International Conference on Autonomous Agents and Multiagent Systems (AAMAS 2026)
        </div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>
</div>
</div>
</dd>
<dt>
<a name="item5">[5]</a>
<a href="/abs/2602.14815" id="2602.14815" title="Abstract">
        arXiv:2602.14815
      </a>

        [<a aria-labelledby="pdf-2602.14815" href="/pdf/2602.14815" id="pdf-2602.14815" title="Download PDF">pdf</a>, <a aria-labelledby="html-2602.14815" href="https://arxiv.org/html/2602.14815v1" id="html-2602.14815" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>, <a aria-labelledby="oth-2602.14815" href="/format/2602.14815" id="oth-2602.14815" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          Revenue Guarantees in Autobidding Platforms
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Caragiannis,+I">Ioannis Caragiannis</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ipsen,+A+B">Anders Bo Ipsen</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Skoulakis,+S">Stratis Skoulakis</a></div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>
</div>
</div>
</dd>
<dt>
<a name="item6">[6]</a>
<a href="/abs/2602.14668" id="2602.14668" title="Abstract">
        arXiv:2602.14668
      </a>

        [<a aria-labelledby="pdf-2602.14668" href="/pdf/2602.14668" id="pdf-2602.14668" title="Download PDF">pdf</a>, <a aria-labelledby="html-2602.14668" href="https://arxiv.org/html/2602.14668v1" id="html-2602.14668" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>, <a aria-labelledby="oth-2602.14668" href="/format/2602.14668" id="oth-2602.14668" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          Near-Optimal Best-of-Both-Worlds Fairness for Few Agents
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Babaioff,+M">Moshe Babaioff</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Frosh,+G">Gefen Frosh</a></div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>
</div>
</div>
</dd>
<dt>
<a name="item7">[7]</a>
<a href="/abs/2602.14476" id="2602.14476" title="Abstract">
        arXiv:2602.14476
      </a>

        [<a aria-labelledby="pdf-2602.14476" href="/pdf/2602.14476" id="pdf-2602.14476" title="Download PDF">pdf</a>, <a aria-labelledby="html-2602.14476" href="https://arxiv.org/html/2602.14476v1" id="html-2602.14476" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>, <a aria-labelledby="oth-2602.14476" href="/format/2602.14476" id="oth-2602.14476" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          Truthful Reverse Auctions for Adaptive Selection via Contextual Multi-Armed Bandits
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Patra,+P">Pronoy Patra</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Damle,+S">Sankarshan Damle</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Padala,+M">Manisha Padala</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Gujar,+S">Sujit Gujar</a></div>
<div class="list-comments mathjax"><span class="descriptor">Comments:</span>
          20 pages, 6 figures
        </div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>
</div>
</div>
</dd>
<dt>
<a name="item8">[8]</a>
<a href="/abs/2602.14331" id="2602.14331" title="Abstract">
        arXiv:2602.14331
      </a>

        [<a aria-labelledby="pdf-2602.14331" href="/pdf/2602.14331" id="pdf-2602.14331" title="Download PDF">pdf</a>, <a aria-labelledby="oth-2602.14331" href="/format/2602.14331" id="oth-2602.14331" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          A Bayesian Framework for Human-AI Collaboration: Complementarity and Correlation Neglect
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Amin,+S">Saurabh Amin</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Bennouna,+A">Amine Bennouna</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Huttenlocher,+D">Daniel Huttenlocher</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kong,+D">Dingwen Kong</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Lyu,+L">Liang Lyu</a>, <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ozdaglar,+A">Asuman Ozdaglar</a></div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>; Human-Computer Interaction (cs.HC); Theoretical Economics (econ.TH)
        </div>
</div>
</dd>
<dt>
<a name="item9">[9]</a>
<a href="/abs/2602.14321" id="2602.14321" title="Abstract">
        arXiv:2602.14321
      </a>

        [<a aria-labelledby="pdf-2602.14321" href="/pdf/2602.14321" id="pdf-2602.14321" title="Download PDF">pdf</a>, <a aria-labelledby="html-2602.14321" href="https://arxiv.org/html/2602.14321v1" id="html-2602.14321" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>, <a aria-labelledby="oth-2602.14321" href="/format/2602.14321" id="oth-2602.14321" title="Other formats">other</a>]
    </dt>
<dd>
<div class="meta">
<div class="list-title mathjax"><span class="descriptor">Title:</span>
          Offline Learning of Nash Stable Coalition Structures with Possibly Overlapping Coalitions
        </div>
<div class="list-authors"><a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Cohen,+S">Saar Cohen</a></div>
<div class="list-comments mathjax"><span class="descriptor">Comments:</span>
          To Appear in the 25th International Conference on Autonomous Agents and Multiagent Systems (AAMAS), 2026
        </div>
<div class="list-subjects"><span class="descriptor">Subjects:</span>
<span class="primary-subject">Computer Science and Game Theory (cs.GT)</span>; Artificial Intelligence (cs.AI); Machine Learning (cs.LG); Multiagent Systems (cs.MA)
        </div>
</div>
</dd>
<dt>
<a name="item10">[10]</a>

In [113]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <title>
   Computer Science and Game Theory
  </title>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link href="/static/browse/0.3.4/images/icons/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
  <link href="/static/browse/0.3.4/images/icons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
  <link href="/static/browse/0.3.4/images/icons/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
  <link href="/static/browse/0.3.4/images/icons/site.webmanifest" rel="manifest"/>
  <link color="#5bbad5" href="/static/browse/0.3.4/images/icons/safari-pinned-tab.svg" rel="mask-icon"/>
  <meta content="#da532c" name="msapplication-TileColor"/>
  <meta content="#ffffff" name="theme-color"/>
  <link href="/static/browse/0.3.4/css/arXiv.css?v=20241206" media="screen" rel="stylesheet" type="text/css">
   <link href="/static/browse/0.3.4/css/arXiv-print.css?v=20200611" media="print" rel="stylesheet" type="text/css">
    <link href="/static/browse/0.3.4/css/browse_search.css" media="screen" rel="stylesheet" type="text/css">
     <script language="javascript" src="/static/browse/0.3.4/js/accordion.js">
     </script>
     <script language="javascript" src="/static/browse/0.3.4/js/optin-modal.js?v=20250819">
     </script>
     <script src="/static/browse/0.3.4/js/mathjaxToggle.min.js" type="text/javascript">
     </script>
     <script language="javascript" type="text/javascript">
      mathjaxToggle();
     </script>
    </link>
   </link>
  </link>
 </head>
 <body class="with-cu-identity">
  <div class="flex-wrap-footer">
   <header>
    <a class="is-sr-only" href="#content">
     Skip to main content
    </a>
    <!-- start desktop header -->
    <div class="columns is-vcentered is-hidden-mobile" id="cu-identity">
     <div class="column" id="cu-logo">
      <a href="https://www.cornell.edu/">
       <img alt="Cornell University" src="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg"/>
      </a>
     </div>
     <!-- /from April 7 at 1:00 AM to May 29 at 21:40 -->
     <!-- /from May 2 at 1:00 AM to May 5 at 9:45 AM -->
     <div class="column" id="support-ack">
      <span id="support-ack-url">
       We gratefully acknowledge support from the Simons Foundation,
       <a href="https://info.arxiv.org/about/ourmembers.html">
        member institutions
       </a>
       , and all contributors.
      </span>
      <a class="btn-header-donate" href="https://info.arxiv.org/about/donate.html">
       Donate
      </a>
     </div>
    </div>
    <div class="is-hidden-mobile" id="header">
     <a aria-hidden="true" href="/IgnoreMe" tabindex="-1">
     </a>
     <div class="header-breadcrumbs">
      <a href="/">
       <img alt="arxiv logo" src="/static/browse/0.3.4/images/arxiv-logo-one-color-white.svg" style="height:40px;"/>
      </a>
      <span>
       &gt;
      </span>
      <a href="/list/cs.GT/recent">
       cs.GT
      </a>
     </div>
     <div class="columns is-vcentered is-mobile" style="justify-content: flex-end;">
     </div>
     <div class="search-block level-right">
      <form action="https://arxiv.org/search" class="level-item mini-search" method="GET">
       <div class="field has-addons">
        <div class="control">
         <input aria-label="Search term or terms" class="input is-small" name="query" placeholder="Search..." type="text"/>
         <p class="help">
          <a href="https://info.arxiv.org/help">
           Help
          </a>
          |
          <a href="https://arxiv.org/search/advanced">
           Advanced Search
          </a>
         </p>
        </div>
        <div class="control">
         <div class="select is-small">
          <select aria-label="Field to search" name="searchtype">
           <option selected="selected" value="all">
            All fields
           </option>
           <option value="title">
            Title
           </option>
           <option value="author">
            Author
           </option>
           <option value="abstract">
            Abstract
           </option>
           <option value="comments">
            Comments
           </option>
           <option value="journal_ref">
            Journal reference
           </option>
           <option value="acm_class">
            ACM classification
           </option>
           <option value="msc_class">
            MSC classification
           </option>
           <option value="report_num">
            Report number
           </option>
           <option value="paper_id">
            arXiv identifier
           </option>
           <option value="doi">
            DOI
           </option>
           <option value="orcid">
            ORCID
           </option>
           <option value="author_id">
            arXiv author ID
           </option>
           <option value="help">
            Help pages
           </option>
           <option value="full_text">
            Full text
           </option>
          </select>
         </div>
        </div>
        <input name="source" type="hidden" value="header"/>
        <button class="button is-small is-cul-darker">
         Search
        </button>
       </div>
      </form>
     </div>
    </div>
    <!-- /end desktop header -->
    <div class="mobile-header">
     <div class="columns is-mobile">
      <div class="column logo-arxiv">
       <a href="https://arxiv.org/">
        <img alt="arXiv logo" src="/static/browse/0.3.4/images/arxiv-logomark-small-white.svg" style="height:60px;"/>
       </a>
      </div>
      <div class="column logo-cornell">
       <a href="https://www.cornell.edu/">
        <picture>
         <source media="(min-width: 501px)" sizes="400w" srcset="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg  400w"/>
         <source srcset="/static/browse/0.3.4/images/icons/cu/cornell_seal_simple_black.svg 2x"/>
         <img alt="Cornell University Logo" src="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg"/>
        </picture>
       </a>
      </div>
      <div class="column nav" id="toggle-container" role="menubar">
       <button class="toggle-control">
        <svg class="icon filter-white" viewbox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
         <title>
          open search
         </title>
         <path d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z">
         </path>
        </svg>
       </button>
       <div class="mobile-toggle-block toggle-target">
        <form action="https://arxiv.org/search" class="mobile-search-form" method="GET">
         <div class="field has-addons">
          <input aria-label="Search term or terms" class="input" name="query" placeholder="Search..." type="text">
           <input name="source" type="hidden" value="header"/>
           <input name="searchtype" type="hidden" value="all"/>
           <button class="button">
            GO
           </button>
          </input>
         </div>
        </form>
       </div>
       <button class="toggle-control">
        <svg class="icon filter-white" role="menu" viewbox="0 0 448 512" xmlns="http://www.w3.org/2000/svg">
         <title>
          open navigation menu
         </title>
         <path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z">
         </path>
        </svg>
       </button>
       <div class="mobile-toggle-block toggle-target">
        <nav aria-labelledby="mobilemenulabel" class="mobile-menu">
         <h2 id="mobilemenulabel">
          quick links
         </h2>
         <ul>
          <li>
           <a href="https://arxiv.org/login">
            Login
           </a>
          </li>
          <li>
           <a href="https://info.arxiv.org/help">
            Help Pages
           </a>
          </li>
          <li>
           <a href="https://info.arxiv.org/about">
            About
           </a>
          </li>
         </ul>
        </nav>
       </div>
      </div>
     </div>
    </div>
    <!-- /end mobile-header -->
   </header>
   <main>
    <div id="content">
     <div id="content-inner">
      <div id="dlpage">
       <h1>
        Computer Science and Game Theory
       </h1>
       <h2>
        Authors and titles for recent submissions
       </h2>
       <ul>
        <li>
         <a href="/list/cs.GT/recent?skip=0&amp;show=50">
          Tue, 17 Feb 2026
         </a>
        </li>
        <li>
         <a href="/list/cs.GT/recent?skip=25&amp;show=50">
          Mon, 16 Feb 2026
         </a>
        </li>
        <li>
         <a href="/list/cs.GT/recent?skip=38&amp;show=50">
          Fri, 13 Feb 2026
         </a>
        </li>
        <li>
         <a href="/list/cs.GT/recent?skip=61&amp;show=50">
          Thu, 12 Feb 2026
         </a>
        </li>
        <li>
         <a href="/list/cs.GT/recent?skip=74&amp;show=50">
          Wed, 11 Feb 2026
         </a>
        </li>
       </ul>
       <p>
        See today's
        <a aria-labelledby="new-cs.GT" href="/list/cs.GT/new" id="new-cs.GT">
         new
        </a>
        changes
       </p>
       <div class="paging">
        Total of 82 entries :
        <span>
         1-50
        </span>
        <a href="/list/cs.GT/recent?skip=50&amp;show=50">
         51-82
        </a>
       </div>
       <div class="morefewer">
        Showing up to 50 entries per page:
        <a href="/list/cs.GT/recent?skip=0&amp;show=25" rel="nofollow">
         fewer
        </a>
        |
        <span style="color: #454545">
         more
        </span>
        |
        <a href="/list/cs.GT/recent?skip=0&amp;show=2000" rel="nofollow">
         all
        </a>
       </div>
       <dl id="articles">
        <h3>
         Tue, 17 Feb 2026 (showing 25 of 25 entries )
        </h3>
        <dt>
         <a name="item1">
          [1]
         </a>
         <a href="/abs/2602.14966" id="2602.14966" title="Abstract">
          arXiv:2602.14966
         </a>
         [
         <a aria-labelledby="pdf-2602.14966" href="/pdf/2602.14966" id="pdf-2602.14966" title="Download PDF">
          pdf
         </a>
         ,
         <a aria-labelledby="html-2602.14966" href="https://arxiv.org/html/2602.14966v1" id="html-2602.14966" rel="noopener noreferrer" target="_blank" title="View HTML">
          html
         </a>
         ,
         <a aria-labelledby="oth-2602.14966" href="/format/2602.14966" id="oth-2602.14966" title="Other formats">
          other
         </a>
         ]
        </dt>
        <dd>
         <div class="meta">
          <div class="list-title mathjax">
           <span class="descriptor">
            Title:
           </span>
           Robust Value Maximization in Challenge the Champ Tournaments with Probabilistic Outcomes
          </div>
          <div class="list-authors">
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Bhaskar,+U">
            Umang Bhaskar
           </a>
           ,
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Chaudhary,+J">
            Juhi Chaudhary
           </a>
           ,
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Gupta,+S">
            Sushmita Gupta
           </a>
           ,
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Jain,+P">
            Pallavi Jain
           </a>
           ,
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Seetharaman,+S">
            Sanjay Seetharaman
           </a>
          </div>
          <div class="list-comments mathjax">
           <span class="descriptor">
            Comments:
           </span>
           28 pages; full version of the paper to appear in AAMAS 2026
          </div>
          <div class="list-subjects">
           <span class="descriptor">
            Subjects:
           </span>
           <span class="primary-subject">
            Computer Science and Game Theory (cs.GT)
           </span>
           ; Data Structures and Algorithms (cs.DS)
          </div>
         </div>
        </dd>
        <dt>
         <a name="item2">
          [2]
         </a>
         <a href="/abs/2602.14961" id="2602.14961" title="Abstract">
          arXiv:2602.14961
         </a>
         [
         <a aria-labelledby="pdf-2602.14961" href="/pdf/2602.14961" id="pdf-2602.14961" title="Download PDF">
          pdf
         </a>
         ,
         <a aria-labelledby="html-2602.14961" href="https://arxiv.org/html/2602.14961v1" id="html-2602.14961" rel="noopener noreferrer" target="_blank" title="View HTML">
          html
         </a>
         ,
         <a aria-labelledby="oth-2602.14961" href="/format/2602.14961" id="oth-2602.14961" title="Other formats">
          other
         </a>
         ]
        </dt>
        <dd>
         <div class="meta">
          <div class="list-title mathjax">
           <span class="descriptor">
            Title:
           </span>
           The Distortion of Stable Matching
          </div>
          <div class="list-authors">
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Filos-Ratsikas,+A">
            Aris Filos-Ratsikas
           </a>
           ,
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kalantzis,+G">
            Georgios Kalantzis
           </a>
          </div>
          <div class="list-subjects">
           <span class="descriptor">
            Subjects:
           </span>
           <span class="primary-subject">
            Computer Science and Game Theory (cs.GT)
           </span>
          </div>
         </div>
        </dd>
        <dt>
         <a name="item3">
          [3]
         </a>
         <a href="/abs/2602.14858" id="2602.14858" title="Abstract">
          arXiv:2602.14858
         </a>
         [
         <a aria-labelledby="pdf-2602.14858" href="/pdf/2602.14858" id="pdf-2602.14858" title="Download PDF">
          pdf
         </a>
         ,
         <a aria-labelledby="html-2602.14858" href="https://arxiv.org/html/2602.14858v1" id="html-2602.14858" rel="noopener noreferrer" target="_blank" title="View HTML">
          html
         </a>
         ,
         <a aria-labelledby="oth-2602.14858" href="/format/2602.14858" id="oth-2602.14858" title="Other formats">
          other
         </a>
         ]
        </dt>
        <dd>
         <div class="meta">
          <div class="list-title mathjax">
           <span class="descriptor">
            Title:
           </span>
           Thermal Min-Max Games: Unifying Bounded Rationality and Typical-Case Equilibrium
          </div>
          <div class="list-authors">
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ichikawa,+Y">
            Yuma Ichikawa
           </a>
          </div>
          <div class="list-comments mathjax">
           <span class="descriptor">
            Comments:
           </span>
           31 pages, 4 figures
          </div>
          <div class="list-subjects">
           <span class="descriptor">
            Subjects:
           </span>
           <span class="primary-subject">
            Computer Science and Game Theory (cs.GT)
           </span>
           ; Disordered Systems and Neural Networks (cond-mat.dis-nn)
          </div>
         </div>
        </dd>
        <dt>
         <a name="item4">
          [4]
         </a>
         <a href="/abs/2602.14850" id="2602.14850" title="Abstract">
          arXiv:2602.14850
         </a>
         [
         <a aria-labelledby="pdf-2602.14850" href="/pdf/2602.14850" id="pdf-2602.14850" title="Download PDF">
          pdf
         </a>
         ,
         <a aria-labelledby="html-2602.14850" href="https://arxiv.org/html/2602.14850v1" id="html-2602.14850" rel="noopener noreferrer" target="_blank" title="View HTML">
          html
         </a>
         ,
         <a aria-labelledby="oth-2602.14850" href="/format/2602.14850" id="oth-2602.14850" title="Other formats">
          other
         </a>
         ]
        </dt>
        <dd>
         <div class="meta">
          <div class="list-title mathjax">
           <span class="descriptor">
            Title:
           </span>
           Fair Allocation with Initial Utilities
          </div>
          <div class="list-authors">
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Boehmer,+N">
            Niclas Boehmer
           </a>
           ,
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kreisel,+L">
            Luca Kreisel
           </a>
          </div>
          <div class="list-comments mathjax">
           <span class="descriptor">
            Comments:
           </span>
           34 pages. An extended abstract is scheduled to appear in the proceedings of the 25th International Conference on Autonomous Agents and Multiagent Systems (AAMAS 2026)
          </div>
          <div class="list-subjects">
           <span class="descriptor">
            Subjects:
           </span>
           <span class="primary-subject">
            Computer Science and Game Theory (cs.GT)
           </span>
          </div>
         </div>
        </dd>
        <dt>
         <a name="item5">
          [5]
         </a>
         <a href="/abs/2602.14815" id="2602.14815" title="Abstract">
          arXiv:2602.14815
         </a>
         [
         <a aria-labelledby="pdf-2602.14815" href="/pdf/2602.14815" id="pdf-2602.14815" title="Download PDF">
          pdf
         </a>
         ,
         <a aria-labelledby="html-2602.14815" href="https://arxiv.org/html/2602.14815v1" id="html-2602.14815" rel="noopener noreferrer" target="_blank" title="View HTML">
          html
         </a>
         ,
         <a aria-labelledby="oth-2602.14815" href="/format/2602.14815" id="oth-2602.14815" title="Other formats">
          other
         </a>
         ]
        </dt>
        <dd>
         <div class="meta">
          <div class="list-title mathjax">
           <span class="descriptor">
            Title:
           </span>
           Revenue Guarantees in Autobidding Platforms
          </div>
          <div class="list-authors">
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Caragiannis,+I">
            Ioannis Caragiannis
           </a>
           ,
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ipsen,+A+B">
            Anders Bo Ipsen
           </a>
           ,
           <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Skoulakis,+S">
            Stratis Skoulakis
           </a>
          </div>
          <div class="list-subjects">
           <span class="descriptor">
            Subjects:
           </span>
           <span class="primary-subject">
            Computer Science and Game Theory (cs.GT)
           </span>
          </div>
         </div>
        </dd>
        <dt>
         <a name="item6">
          [6]
         </a>
         <a href="/abs/2602.14668" id="2602.14668" title="Abstract">
          arXiv:2602.14668
         </a>
         [
         <a aria-labelledby="pdf-2602.14668" href="/pdf/2602.14668" id="pdf-2602.14668" title="Download PDF">
          pdf
         </a>
         ,

In [115]:
soup.find_all('a')

[<a class="is-sr-only" href="#content">Skip to main content</a>,
 <a href="https://www.cornell.edu/"><img alt="Cornell University" src="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg"/></a>,
 <a href="https://info.arxiv.org/about/ourmembers.html">member institutions</a>,
 <a class="btn-header-donate" href="https://info.arxiv.org/about/donate.html">Donate</a>,
 <a aria-hidden="true" href="/IgnoreMe" tabindex="-1"></a>,
 <a href="/"><img alt="arxiv logo" src="/static/browse/0.3.4/images/arxiv-logo-one-color-white.svg" style="height:40px;"/></a>,
 <a href="/list/cs.GT/recent">cs.GT</a>,
 <a href="https://info.arxiv.org/help">Help</a>,
 <a href="https://arxiv.org/search/advanced">Advanced Search</a>,
 <a href="https://arxiv.org/"><img alt="arXiv logo" src="/static/browse/0.3.4/images/arxiv-logomark-small-white.svg" style="height:60px;"/></a>,
 <a href="https://www.cornell.edu/">
 <picture>
 <source media="(min-width: 501px)" sizes="400w" srcset="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg  400w"/>
 <source srcset="/static/browse/0.3.4/images/icons/cu/cornell_seal_simple_black.svg 2x"/>
 <img alt="Cornell University Logo" src="/static/browse/0.3.4/images/icons/cu/cornell-reduced-white-SMALL.svg"/>
 </picture>
 </a>,
 <a href="https://arxiv.org/login">Login</a>,
 <a href="https://info.arxiv.org/help">Help Pages</a>,
 <a href="https://info.arxiv.org/about">About</a>,
 <a href="/list/cs.GT/recent?skip=0&amp;show=50">
           Tue, 17 Feb 2026
         </a>,
 <a href="/list/cs.GT/recent?skip=25&amp;show=50">
           Mon, 16 Feb 2026
         </a>,
 <a href="/list/cs.GT/recent?skip=38&amp;show=50">
           Fri, 13 Feb 2026
         </a>,
 <a href="/list/cs.GT/recent?skip=61&amp;show=50">
           Thu, 12 Feb 2026
         </a>,
 <a href="/list/cs.GT/recent?skip=74&amp;show=50">
           Wed, 11 Feb 2026
         </a>,
 <a aria-labelledby="new-cs.GT" href="/list/cs.GT/new" id="new-cs.GT">new</a>,
 <a href="/list/cs.GT/recent?skip=50&amp;show=50">51-82</a>,
 <a href="/list/cs.GT/recent?skip=0&amp;show=25" rel="nofollow">
       fewer</a>,
 <a href="/list/cs.GT/recent?skip=0&amp;show=2000" rel="nofollow">
       all</a>,
 <a name="item1">[1]</a>,
 <a href="/abs/2602.14966" id="2602.14966" title="Abstract">
         arXiv:2602.14966
       </a>,
 <a aria-labelledby="pdf-2602.14966" href="/pdf/2602.14966" id="pdf-2602.14966" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14966" href="https://arxiv.org/html/2602.14966v1" id="html-2602.14966" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14966" href="/format/2602.14966" id="oth-2602.14966" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Bhaskar,+U">Umang Bhaskar</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Chaudhary,+J">Juhi Chaudhary</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Gupta,+S">Sushmita Gupta</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Jain,+P">Pallavi Jain</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Seetharaman,+S">Sanjay Seetharaman</a>,
 <a name="item2">[2]</a>,
 <a href="/abs/2602.14961" id="2602.14961" title="Abstract">
         arXiv:2602.14961
       </a>,
 <a aria-labelledby="pdf-2602.14961" href="/pdf/2602.14961" id="pdf-2602.14961" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14961" href="https://arxiv.org/html/2602.14961v1" id="html-2602.14961" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14961" href="/format/2602.14961" id="oth-2602.14961" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Filos-Ratsikas,+A">Aris Filos-Ratsikas</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kalantzis,+G">Georgios Kalantzis</a>,
 <a name="item3">[3]</a>,
 <a href="/abs/2602.14858" id="2602.14858" title="Abstract">
         arXiv:2602.14858
       </a>,
 <a aria-labelledby="pdf-2602.14858" href="/pdf/2602.14858" id="pdf-2602.14858" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14858" href="https://arxiv.org/html/2602.14858v1" id="html-2602.14858" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14858" href="/format/2602.14858" id="oth-2602.14858" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ichikawa,+Y">Yuma Ichikawa</a>,
 <a name="item4">[4]</a>,
 <a href="/abs/2602.14850" id="2602.14850" title="Abstract">
         arXiv:2602.14850
       </a>,
 <a aria-labelledby="pdf-2602.14850" href="/pdf/2602.14850" id="pdf-2602.14850" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14850" href="https://arxiv.org/html/2602.14850v1" id="html-2602.14850" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14850" href="/format/2602.14850" id="oth-2602.14850" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Boehmer,+N">Niclas Boehmer</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kreisel,+L">Luca Kreisel</a>,
 <a name="item5">[5]</a>,
 <a href="/abs/2602.14815" id="2602.14815" title="Abstract">
         arXiv:2602.14815
       </a>,
 <a aria-labelledby="pdf-2602.14815" href="/pdf/2602.14815" id="pdf-2602.14815" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14815" href="https://arxiv.org/html/2602.14815v1" id="html-2602.14815" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14815" href="/format/2602.14815" id="oth-2602.14815" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Caragiannis,+I">Ioannis Caragiannis</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ipsen,+A+B">Anders Bo Ipsen</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Skoulakis,+S">Stratis Skoulakis</a>,
 <a name="item6">[6]</a>,
 <a href="/abs/2602.14668" id="2602.14668" title="Abstract">
         arXiv:2602.14668
       </a>,
 <a aria-labelledby="pdf-2602.14668" href="/pdf/2602.14668" id="pdf-2602.14668" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14668" href="https://arxiv.org/html/2602.14668v1" id="html-2602.14668" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14668" href="/format/2602.14668" id="oth-2602.14668" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Babaioff,+M">Moshe Babaioff</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Frosh,+G">Gefen Frosh</a>,
 <a name="item7">[7]</a>,
 <a href="/abs/2602.14476" id="2602.14476" title="Abstract">
         arXiv:2602.14476
       </a>,
 <a aria-labelledby="pdf-2602.14476" href="/pdf/2602.14476" id="pdf-2602.14476" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14476" href="https://arxiv.org/html/2602.14476v1" id="html-2602.14476" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14476" href="/format/2602.14476" id="oth-2602.14476" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Patra,+P">Pronoy Patra</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Damle,+S">Sankarshan Damle</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Padala,+M">Manisha Padala</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Gujar,+S">Sujit Gujar</a>,
 <a name="item8">[8]</a>,
 <a href="/abs/2602.14331" id="2602.14331" title="Abstract">
         arXiv:2602.14331
       </a>,
 <a aria-labelledby="pdf-2602.14331" href="/pdf/2602.14331" id="pdf-2602.14331" title="Download PDF">pdf</a>,
 <a aria-labelledby="oth-2602.14331" href="/format/2602.14331" id="oth-2602.14331" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Amin,+S">Saurabh Amin</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Bennouna,+A">Amine Bennouna</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Huttenlocher,+D">Daniel Huttenlocher</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kong,+D">Dingwen Kong</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Lyu,+L">Liang Lyu</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ozdaglar,+A">Asuman Ozdaglar</a>,
 <a name="item9">[9]</a>,
 <a href="/abs/2602.14321" id="2602.14321" title="Abstract">
         arXiv:2602.14321
       </a>,
 <a aria-labelledby="pdf-2602.14321" href="/pdf/2602.14321" id="pdf-2602.14321" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14321" href="https://arxiv.org/html/2602.14321v1" id="html-2602.14321" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14321" href="/format/2602.14321" id="oth-2602.14321" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Cohen,+S">Saar Cohen</a>,
 <a name="item10">[10]</a>,
 <a href="/abs/2602.14278" id="2602.14278" title="Abstract">
         arXiv:2602.14278
       </a>,
 <a aria-labelledby="pdf-2602.14278" href="/pdf/2602.14278" id="pdf-2602.14278" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14278" href="https://arxiv.org/html/2602.14278v1" id="html-2602.14278" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14278" href="/format/2602.14278" id="oth-2602.14278" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Kejriwal,+M">Mayank Kejriwal</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Thomas,+S">Shilpa Thomas</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Li,+H">Hongyu Li</a>,
 <a name="item11">[11]</a>,
 <a href="/abs/2602.14223" id="2602.14223" title="Abstract">
         arXiv:2602.14223
       </a>,
 <a aria-labelledby="pdf-2602.14223" href="/pdf/2602.14223" id="pdf-2602.14223" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14223" href="https://arxiv.org/html/2602.14223v1" id="html-2602.14223" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14223" href="/format/2602.14223" id="oth-2602.14223" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Boonen,+T+J">Tim J. Boonen</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ng,+K+T+H">Kenneth Tsz Hin Ng</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ng,+T+W">Tak Wa Ng</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Nguyen,+T">Thai Nguyen</a>,
 <a name="item12">[12]</a>,
 <a href="/abs/2602.14120" id="2602.14120" title="Abstract">
         arXiv:2602.14120
       </a>,
 <a aria-labelledby="pdf-2602.14120" href="/pdf/2602.14120" id="pdf-2602.14120" title="Download PDF">pdf</a>,
 <a aria-labelledby="oth-2602.14120" href="/format/2602.14120" id="oth-2602.14120" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Carbajal,+J+C">Juan Carlos Carbajal</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Mualem,+A">Ahuva Mualem</a>,
 <a name="item13">[13]</a>,
 <a href="/abs/2602.14076" id="2602.14076" title="Abstract">
         arXiv:2602.14076
       </a>,
 <a aria-labelledby="pdf-2602.14076" href="/pdf/2602.14076" id="pdf-2602.14076" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14076" href="https://arxiv.org/html/2602.14076v1" id="html-2602.14076" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14076" href="/format/2602.14076" id="oth-2602.14076" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Meir,+R">Reshef Meir</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Wagner,+J">Jonathan Wagner</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ben-Porat,+O">Omer Ben-Porat</a>,
 <a name="item14">[14]</a>,
 <a href="/abs/2602.13897" id="2602.13897" title="Abstract">
         arXiv:2602.13897
       </a>,
 <a aria-labelledby="pdf-2602.13897" href="/pdf/2602.13897" id="pdf-2602.13897" title="Download PDF">pdf</a>,
 <a aria-labelledby="oth-2602.13897" href="/format/2602.13897" id="oth-2602.13897" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Chaudhury,+B+R">Bhaskar Ray Chaudhury</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Garg,+J">Jugal Garg</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Sharma,+E">Eklavya Sharma</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Song,+J">Jiaxin Song</a>,
 <a name="item15">[15]</a>,
 <a href="/abs/2602.13451" id="2602.13451" title="Abstract">
         arXiv:2602.13451
       </a>,
 <a aria-labelledby="pdf-2602.13451" href="/pdf/2602.13451" id="pdf-2602.13451" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.13451" href="https://arxiv.org/html/2602.13451v1" id="html-2602.13451" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.13451" href="/format/2602.13451" id="oth-2602.13451" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Collina,+N">Natalie Collina</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Goel,+S">Surbhi Goel</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Roth,+A">Aaron Roth</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Shi,+M">Mirah Shi</a>,
 <a name="item16">[16]</a>,
 <a href="/abs/2602.13422" id="2602.13422" title="Abstract">
         arXiv:2602.13422
       </a>,
 <a aria-labelledby="pdf-2602.13422" href="/pdf/2602.13422" id="pdf-2602.13422" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.13422" href="https://arxiv.org/html/2602.13422v1" id="html-2602.13422" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.13422" href="/format/2602.13422" id="oth-2602.13422" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Liu,+Y">Yuxi Liu</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Peng,+J">Junqiang Peng</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Xiao,+M">Mingyu Xiao</a>,
 <a name="item17">[17]</a>,
 <a href="/abs/2602.14816" id="2602.14816" title="Abstract">
         arXiv:2602.14816
       </a>,
 <a aria-labelledby="pdf-2602.14816" href="/pdf/2602.14816" id="pdf-2602.14816" title="Download PDF">pdf</a>,
 <a aria-labelledby="oth-2602.14816" href="/format/2602.14816" id="oth-2602.14816" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/econ?searchtype=author&amp;query=Brandt,+F">Felix Brandt</a>,
 <a href="https://arxiv.org/search/econ?searchtype=author&amp;query=Chen,+H">Haoyuan Chen</a>,
 <a href="https://arxiv.org/search/econ?searchtype=author&amp;query=Dong,+C">Chris Dong</a>,
 <a href="https://arxiv.org/search/econ?searchtype=author&amp;query=Lederer,+P">Patrick Lederer</a>,
 <a href="https://arxiv.org/search/econ?searchtype=author&amp;query=Schlenga,+A">Alexander Schlenga</a>,
 <a name="item18">[18]</a>,
 <a href="/abs/2602.14740" id="2602.14740" title="Abstract">
         arXiv:2602.14740
       </a>,
 <a aria-labelledby="pdf-2602.14740" href="/pdf/2602.14740" id="pdf-2602.14740" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14740" href="https://arxiv.org/html/2602.14740v1" id="html-2602.14740" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14740" href="/format/2602.14740" id="oth-2602.14740" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Payne,+K">Kenneth Payne</a>,
 <a name="item19">[19]</a>,
 <a href="/abs/2602.14553" id="2602.14553" title="Abstract">
         arXiv:2602.14553
       </a>,
 <a aria-labelledby="pdf-2602.14553" href="/pdf/2602.14553" id="pdf-2602.14553" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14553" href="https://arxiv.org/html/2602.14553v1" id="html-2602.14553" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14553" href="/format/2602.14553" id="oth-2602.14553" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Lin,+Q">Qinqi Lin</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Ding,+N">Ningning Ding</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Duan,+L">Lingjie Duan</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Huang,+J">Jianwei Huang</a>,
 <a name="item20">[20]</a>,
 <a href="/abs/2602.14471" id="2602.14471" title="Abstract">
         arXiv:2602.14471
       </a>,
 <a aria-labelledby="pdf-2602.14471" href="/pdf/2602.14471" id="pdf-2602.14471" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.14471" href="https://arxiv.org/html/2602.14471v1" id="html-2602.14471" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.14471" href="/format/2602.14471" id="oth-2602.14471" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Mumcu,+F">Furkan Mumcu</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Yilmaz,+Y">Yasin Yilmaz</a>,
 <a name="item21">[21]</a>,
 <a href="/abs/2602.13894" id="2602.13894" title="Abstract">
         arXiv:2602.13894
       </a>,
 <a aria-labelledby="pdf-2602.13894" href="/pdf/2602.13894" id="pdf-2602.13894" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.13894" href="https://arxiv.org/html/2602.13894v1" id="html-2602.13894" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.13894" href="/format/2602.13894" id="oth-2602.13894" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/econ?searchtype=author&amp;query=Dhar,+M">Manik Dhar</a>,
 <a href="https://arxiv.org/search/econ?searchtype=author&amp;query=Mittal,+K">Kunal Mittal</a>,
 <a href="https://arxiv.org/search/econ?searchtype=author&amp;query=Thomas,+C">Clayton Thomas</a>,
 <a name="item22">[22]</a>,
 <a href="/abs/2602.13882" id="2602.13882" title="Abstract">
         arXiv:2602.13882
       </a>,
 <a aria-labelledby="pdf-2602.13882" href="/pdf/2602.13882" id="pdf-2602.13882" title="Download PDF">pdf</a>,
 <a aria-labelledby="html-2602.13882" href="https://arxiv.org/html/2602.13882v1" id="html-2602.13882" rel="noopener noreferrer" target="_blank" title="View HTML">html</a>,
 <a aria-labelledby="oth-2602.13882" href="/format/2602.13882" id="oth-2602.13882" title="Other formats">other</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Gao,+Y">Yixiao Gao</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Li,+F">Fei Li</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Shi,+R">Ruizhe Shi</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Cheng,+R">Ruizhi Cheng</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Zhang,+J">Jean Zhang</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Han,+B">Bo Han</a>,
 <a href="https://arxiv.org/search/cs?searchtype=author&amp;query=Chen,+S">Songqing Chen</a>,
 <a name="item23">[23]</a>,
 <a href="/abs/2602.13510" id="2602.13510" title="Abstract">
         arXiv:2602.13510

In [213]:
url1 = "https://arxiv.org/list/cs.GT/recent?skip=0&show=100"
res1 = requests.get(url1)
soup = BeautifulSoup(res1.text, "html.parser")
article = soup.find("dl")

dts = article.find_all("dt")
dds = article.find_all("dd")

count = 0
for dt,dd in zip(dts[:20], dds[:20]):
    id = dt.find("a", title="Abstract")
    paper_id = id.text.strip()

    title_div = dd.find("div", class_="list-title mathjax")
    title = title_div.get_text(strip=True).strip()

    author_div = dd.find("div", class_="list-authors")
    author_links = author_div.find_all("a")
    authors = ", ".join([a.text.strip() for a in author_links])

    count+=1

    print("[",count,"]")
    print(paper_id)
    print(title)
    print(authors)
    print()

# for p in papers[:20]:
#     title_div = p.find("div", class_="list-title mathjax")
#     if title_div:
#         title = title_div.get_text(strip=True).replace("Title:", "").strip()
#         print("-", title)

[ 1 ]
arXiv:2602.14966
Title:Robust Value Maximization in Challenge the Champ Tournaments with Probabilistic Outcomes
Umang Bhaskar, Juhi Chaudhary, Sushmita Gupta, Pallavi Jain, Sanjay Seetharaman

[ 2 ]
arXiv:2602.14961
Title:The Distortion of Stable Matching
Aris Filos-Ratsikas, Georgios Kalantzis

[ 3 ]
arXiv:2602.14858
Title:Thermal Min-Max Games: Unifying Bounded Rationality and Typical-Case Equilibrium
Yuma Ichikawa

[ 4 ]
arXiv:2602.14850
Title:Fair Allocation with Initial Utilities
Niclas Boehmer, Luca Kreisel

[ 5 ]
arXiv:2602.14815
Title:Revenue Guarantees in Autobidding Platforms
Ioannis Caragiannis, Anders Bo Ipsen, Stratis Skoulakis

[ 6 ]
arXiv:2602.14668
Title:Near-Optimal Best-of-Both-Worlds Fairness for Few Agents
Moshe Babaioff, Gefen Frosh

[ 7 ]
arXiv:2602.14476
Title:Truthful Reverse Auctions for Adaptive Selection via Contextual Multi-Armed Bandits
Pronoy Patra, Sankarshan Damle, Manisha Padala, Sujit Gujar

[ 8 ]
arXiv:2602.14331
Title:A Bayesian Framework for Human-AI Collaboration: Complementarity and Correlation Neglect
Saurabh Amin, Amine Bennouna, Daniel Huttenlocher, Dingwen Kong, Liang Lyu, Asuman Ozdaglar

[ 9 ]
arXiv:2602.14321
Title:Offline Learning of Nash Stable Coalition Structures with Possibly Overlapping Coalitions
Saar Cohen

[ 10 ]
arXiv:2602.14278
Title:Characterizing Robustness of Strategies to Novelty in Zero-Sum Open Worlds
Mayank Kejriwal, Shilpa Thomas, Hongyu Li

[ 11 ]
arXiv:2602.14223
Title:Pareto and Bowley Reinsurance Games in Peer-to-Peer Insurance
Tim J. Boonen, Kenneth Tsz Hin Ng, Tak Wa Ng, Thai Nguyen

[ 12 ]
arXiv:2602.14120
Title:Evaluating the Performance of Approximation Mechanisms under Budget Constraints
Juan Carlos Carbajal, Ahuva Mualem

[ 13 ]
arXiv:2602.14076
Title:Truthful Reporting of Competence with Minimal Verification
Reshef Meir, Jonathan Wagner, Omer Ben-Porat

[ 14 ]
arXiv:2602.13897
Title:Revenue-Optimal Pricing for Budget-Constrained Buyers in Data Markets
Bhaskar Ray Chaudhury, Jugal Garg, Eklavya Sharma, Jiaxin Song

[ 15 ]
arXiv:2602.13451
Title:Personalization Aids Pluralistic Alignment Under Competition
Natalie Collina, Surbhi Goel, Aaron Roth, Mirah Shi

[ 16 ]
arXiv:2602.13422
Title:The Complexity of Tournament Fixing: Subset FAS Number and Acyclic Neighborhoods
Yuxi Liu, Junqiang Peng, Mingyu Xiao

[ 17 ]
arXiv:2602.14816
Title:Majoritarian Assignment Rules
Felix Brandt, Haoyuan Chen, Chris Dong, Patrick Lederer, Alexander Schlenga

[ 18 ]
arXiv:2602.14740
Title:AI Arms and Influence: Frontier Models Exhibit Sophisticated Reasoning in Simulated Nuclear Crises
Kenneth Payne

[ 19 ]
arXiv:2602.14553
Title:Governing AI Forgetting: Auditing for Machine Unlearning Compliance
Qinqi Lin, Ningning Ding, Lingjie Duan, Jianwei Huang

[ 20 ]
arXiv:2602.14471
Title:Socially-Weighted Alignment: A Game-Theoretic Framework for Multi-Agent LLM Systems
Furkan Mumcu, Yasin Yilmaz

In [282]:
import pandas as pd
rows = []
count=0

for dt,dd in zip(dts[:20], dds[:20]):
    id = dt.find("a", title="Abstract")
    paper_id = id.text.strip()

    title_div = dd.find("div", class_="list-title mathjax")
    title = title_div.get_text(strip=True).replace("Title:", "").strip()

    author_div = dd.find("div", class_="list-authors")
    author_links = author_div.find_all("a")
    authors = ", ".join([a.text.strip() for a in author_links])

    count+=1
    rows.append([count, paper_id, title, authors])

df = pd.DataFrame(rows, columns=["index", "paper_id", "title", "authors"])

In [284]:
from IPython.display import display
display(df)

,index,paper_id,title,authors
0,1,arXiv:2602.14966,Robust Value Maximization in Challenge the Cha...,"Umang Bhaskar, Juhi Chaudhary, Sushmita Gupta,..."
1,2,arXiv:2602.14961,The Distortion of Stable Matching,"Aris Filos-Ratsikas, Georgios Kalantzis"
2,3,arXiv:2602.14858,Thermal Min-Max Games: Unifying Bounded Ration...,Yuma Ichikawa
3,4,arXiv:2602.14850,Fair Allocation with Initial Utilities,"Niclas Boehmer, Luca Kreisel"
4,5,arXiv:2602.14815,Revenue Guarantees in Autobidding Platforms,"Ioannis Caragiannis, Anders Bo Ipsen, Stratis ..."
5,6,arXiv:2602.14668,Near-Optimal Best-of-Both-Worlds Fairness for ...,"Moshe Babaioff, Gefen Frosh"
6,7,arXiv:2602.14476,Truthful Reverse Auctions for Adaptive Selecti...,"Pronoy Patra, Sankarshan Damle, Manisha Padala..."
7,8,arXiv:2602.14331,A Bayesian Framework for Human-AI Collaboratio...,"Saurabh Amin, Amine Bennouna, Daniel Huttenloc..."
8,9,arXiv:2602.14321,Offline Learning of Nash Stable Coalition Stru...,Saar Cohen
9,10,arXiv:2602.14278,Characterizing Robustness of Strategies to Nov...,"Mayank Kejriwal, Shilpa Thomas, Hongyu Li"
10,11,arXiv:2602.14223,Pareto and Bowley Reinsurance Games in Peer-to...,"Tim J. Boonen, Kenneth Tsz Hin Ng, Tak Wa Ng, ..."
11,12,arXiv:2602.14120,Evaluating the Performance of Approximation Me...,"Juan Carlos Carbajal, Ahuva Mualem"
12,13,arXiv:2602.14076,Truthful Reporting of Competence with Minimal ...,"Reshef Meir, Jonathan Wagner, Omer Ben-Porat"
13,14,arXiv:2602.13897,Revenue-Optimal Pricing for Budget-Constrained...,"Bhaskar Ray Chaudhury, Jugal Garg, Eklavya Sha..."
14,15,arXiv:2602.13451,Personalization Aids Pluralistic Alignment Und...,"Natalie Collina, Surbhi Goel, Aaron Roth, Mira..."
15,16,arXiv:2602.13422,The Complexity of Tournament Fixing: Subset FA...,"Yuxi Liu, Junqiang Peng, Mingyu Xiao"
16,17,arXiv:2602.14816,Majoritarian Assignment Rules,"Felix Brandt, Haoyuan Chen, Chris Dong, Patric..."
17,18,arXiv:2602.14740,AI Arms and Influence: Frontier Models Exhibit...,Kenneth Payne
18,19,arXiv:2602.14553,Governing AI Forgetting: Auditing for Machine ...,"Qinqi Lin, Ningning Ding, Lingjie Duan, Jianwe..."
19,20,arXiv:2602.14471,Socially-Weighted Alignment: A Game-Theoretic ...,"Furkan Mumcu, Yasin Yilmaz"

# Clustering

## Lowercase Title

In [286]:
df1 = df.copy()
df1["title"] = df1["title"].str.lower()
df1

,index,paper_id,title,authors
0,1,arXiv:2602.14966,robust value maximization in challenge the cha...,"Umang Bhaskar, Juhi Chaudhary, Sushmita Gupta,..."
1,2,arXiv:2602.14961,the distortion of stable matching,"Aris Filos-Ratsikas, Georgios Kalantzis"
2,3,arXiv:2602.14858,thermal min-max games: unifying bounded ration...,Yuma Ichikawa
3,4,arXiv:2602.14850,fair allocation with initial utilities,"Niclas Boehmer, Luca Kreisel"
4,5,arXiv:2602.14815,revenue guarantees in autobidding platforms,"Ioannis Caragiannis, Anders Bo Ipsen, Stratis ..."
5,6,arXiv:2602.14668,near-optimal best-of-both-worlds fairness for ...,"Moshe Babaioff, Gefen Frosh"
6,7,arXiv:2602.14476,truthful reverse auctions for adaptive selecti...,"Pronoy Patra, Sankarshan Damle, Manisha Padala..."
7,8,arXiv:2602.14331,a bayesian framework for human-ai collaboratio...,"Saurabh Amin, Amine Bennouna, Daniel Huttenloc..."
8,9,arXiv:2602.14321,offline learning of nash stable coalition stru...,Saar Cohen
9,10,arXiv:2602.14278,characterizing robustness of strategies to nov...,"Mayank Kejriwal, Shilpa Thomas, Hongyu Li"
10,11,arXiv:2602.14223,pareto and bowley reinsurance games in peer-to...,"Tim J. Boonen, Kenneth Tsz Hin Ng, Tak Wa Ng, ..."
11,12,arXiv:2602.14120,evaluating the performance of approximation me...,"Juan Carlos Carbajal, Ahuva Mualem"
12,13,arXiv:2602.14076,truthful reporting of competence with minimal ...,"Reshef Meir, Jonathan Wagner, Omer Ben-Porat"
13,14,arXiv:2602.13897,revenue-optimal pricing for budget-constrained...,"Bhaskar Ray Chaudhury, Jugal Garg, Eklavya Sha..."
14,15,arXiv:2602.13451,personalization aids pluralistic alignment und...,"Natalie Collina, Surbhi Goel, Aaron Roth, Mira..."
15,16,arXiv:2602.13422,the complexity of tournament fixing: subset fa...,"Yuxi Liu, Junqiang Peng, Mingyu Xiao"
16,17,arXiv:2602.14816,majoritarian assignment rules,"Felix Brandt, Haoyuan Chen, Chris Dong, Patric..."
17,18,arXiv:2602.14740,ai arms and influence: frontier models exhibit...,Kenneth Payne
18,19,arXiv:2602.14553,governing ai forgetting: auditing for machine ...,"Qinqi Lin, Ningning Ding, Lingjie Duan, Jianwe..."
19,20,arXiv:2602.14471,socially-weighted alignment: a game-theoretic ...,"Furkan Mumcu, Yasin Yilmaz"

## Stopword

In [305]:
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def remove_stopwords(text):
    text = text.lower()
    text = re.sub(r"[^\w\s]", "", text)
    tokens = text.split()
    tokens = [word for word in tokens if word not in ENGLISH_STOP_WORDS]
    return " ".join(tokens)

df1["title"] = df1["title"].apply(remove_stopwords)
df1

,index,paper_id,title,authors
0,1,arXiv:2602.14966,robust value maximization challenge champ tour...,"Umang Bhaskar, Juhi Chaudhary, Sushmita Gupta,..."
1,2,arXiv:2602.14961,distortion stable matching,"Aris Filos-Ratsikas, Georgios Kalantzis"
2,3,arXiv:2602.14858,thermal minmax games unifying bounded rational...,Yuma Ichikawa
3,4,arXiv:2602.14850,fair allocation initial utilities,"Niclas Boehmer, Luca Kreisel"
4,5,arXiv:2602.14815,revenue guarantees autobidding platforms,"Ioannis Caragiannis, Anders Bo Ipsen, Stratis ..."
5,6,arXiv:2602.14668,nearoptimal bestofbothworlds fairness agents,"Moshe Babaioff, Gefen Frosh"
6,7,arXiv:2602.14476,truthful reverse auctions adaptive selection c...,"Pronoy Patra, Sankarshan Damle, Manisha Padala..."
7,8,arXiv:2602.14331,bayesian framework humanai collaboration compl...,"Saurabh Amin, Amine Bennouna, Daniel Huttenloc..."
8,9,arXiv:2602.14321,offline learning nash stable coalition structu...,Saar Cohen
9,10,arXiv:2602.14278,characterizing robustness strategies novelty z...,"Mayank Kejriwal, Shilpa Thomas, Hongyu Li"
10,11,arXiv:2602.14223,pareto bowley reinsurance games peertopeer ins...,"Tim J. Boonen, Kenneth Tsz Hin Ng, Tak Wa Ng, ..."
11,12,arXiv:2602.14120,evaluating performance approximation mechanism...,"Juan Carlos Carbajal, Ahuva Mualem"
12,13,arXiv:2602.14076,truthful reporting competence minimal verifica...,"Reshef Meir, Jonathan Wagner, Omer Ben-Porat"
13,14,arXiv:2602.13897,revenueoptimal pricing budgetconstrained buyer...,"Bhaskar Ray Chaudhury, Jugal Garg, Eklavya Sha..."
14,15,arXiv:2602.13451,personalization aids pluralistic alignment com...,"Natalie Collina, Surbhi Goel, Aaron Roth, Mira..."
15,16,arXiv:2602.13422,complexity tournament fixing subset fas number...,"Yuxi Liu, Junqiang Peng, Mingyu Xiao"
16,17,arXiv:2602.14816,majoritarian assignment rules,"Felix Brandt, Haoyuan Chen, Chris Dong, Patric..."
17,18,arXiv:2602.14740,ai arms influence frontier models exhibit soph...,Kenneth Payne
18,19,arXiv:2602.14553,governing ai forgetting auditing machine unlea...,"Qinqi Lin, Ningning Ding, Lingjie Duan, Jianwe..."
19,20,arXiv:2602.14471,sociallyweighted alignment gametheoretic frame...,"Furkan Mumcu, Yasin Yilmaz"

In [309]:
titles = df1["title"].tolist()
titles

['robust value maximization challenge champ tournaments probabilistic outcomes',
 'distortion stable matching',
 'thermal minmax games unifying bounded rationality typicalcase equilibrium',
 'fair allocation initial utilities',
 'revenue guarantees autobidding platforms',
 'nearoptimal bestofbothworlds fairness agents',
 'truthful reverse auctions adaptive selection contextual multiarmed bandits',
 'bayesian framework humanai collaboration complementarity correlation neglect',
 'offline learning nash stable coalition structures possibly overlapping coalitions',
 'characterizing robustness strategies novelty zerosum open worlds',
 'pareto bowley reinsurance games peertopeer insurance',
 'evaluating performance approximation mechanisms budget constraints',
 'truthful reporting competence minimal verification',
 'revenueoptimal pricing budgetconstrained buyers data markets',
 'personalization aids pluralistic alignment competition',
 'complexity tournament fixing subset fas number acyclic neighborhoods',
 'majoritarian assignment rules',
 'ai arms influence frontier models exhibit sophisticated reasoning simulated nuclear crises',
 'governing ai forgetting auditing machine unlearning compliance',
 'sociallyweighted alignment gametheoretic framework multiagent llm systems']

## bag of words

In [322]:
from sklearn.feature_extraction.text import CountVectorizer
bow_vec = CountVectorizer()
bow_matrix = bow_vec.fit_transform(titles)

In [324]:
bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns = bow_vec.get_feature_names_out()
)

bow_df

,acyclic,adaptive,agents,ai,aids,alignment,allocation,approximation,arms,assignment,...,tournaments,truthful,typicalcase,unifying,unlearning,utilities,value,verification,worlds,zerosum
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
19,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## TF-IDF

In [337]:
tfidf_vec = TfidfVectorizer(
    ngram_range=(1,2)
)
tfidf_matrix = tfidf_vec.fit_transform(titles)

In [343]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vec.get_feature_names_out()
)
tfidf_df.head()

,acyclic,acyclic neighborhoods,adaptive,adaptive selection,agents,ai,ai arms,ai forgetting,aids,aids pluralistic,...,unifying bounded,unlearning,unlearning compliance,utilities,value,value maximization,verification,worlds,zerosum,zerosum open
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.258199,0.258199,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.260178,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.377964,0.000000,0.000000,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0

## Cosine Sim

In [350]:
from sklearn.metrics.pairwise import cosine_similarity
cosine = cosine_similarity(tfidf_matrix)

In [354]:
cosine_df = pd.DataFrame(
    cosine, index = titles,
    columns = titles
)

cosine_df

,robust value maximization challenge champ tournaments probabilistic outcomes,distortion stable matching,thermal minmax games unifying bounded rationality typicalcase equilibrium,fair allocation initial utilities,revenue guarantees autobidding platforms,nearoptimal bestofbothworlds fairness agents,truthful reverse auctions adaptive selection contextual multiarmed bandits,bayesian framework humanai collaboration complementarity correlation neglect,offline learning nash stable coalition structures possibly overlapping coalitions,characterizing robustness strategies novelty zerosum open worlds,pareto bowley reinsurance games peertopeer insurance,evaluating performance approximation mechanisms budget constraints,truthful reporting competence minimal verification,revenueoptimal pricing budgetconstrained buyers data markets,personalization aids pluralistic alignment competition,complexity tournament fixing subset fas number acyclic neighborhoods,majoritarian assignment rules,ai arms influence frontier models exhibit sophisticated reasoning simulated nuclear crises,governing ai forgetting auditing machine unlearning compliance,sociallyweighted alignment gametheoretic framework multiagent llm systems
robust value maximization challenge champ tournaments probabilistic outcomes,1.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
distortion stable matching,0.0,1.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.08636,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
thermal minmax games unifying bounded rationality typicalcase equilibrium,0.0,0.00000,1.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.061249,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
fair allocation initial utilities,0.0,0.00000,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
revenue guarantees autobidding platforms,0.0,0.00000,0.000000,0.0,1.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
nearoptimal bestofbothworlds fairness agents,0.0,0.00000,0.000000,0.0,0.0,1.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
truthful reverse auctions adaptive selection contextual multiarmed bandits,0.0,0.00000,0.000000,0.0,0.0,0.0,1.000000,0.000000,0.00000,0.0,0.000000,0.0,0.067873,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
bayesian framework humanai collaboration complementarity correlation neglect,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,1.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.061039
offline learning nash stable coalition structures possibly overlapping coalitions,0.0,0.08636,0.000000,0.0,0.0,0.0,0.000000,0.000000,1.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
characterizing robustness strategies novelty zerosum open worlds,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,1.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
pareto bowley reinsurance games peertopeer insurance,0.0,0.00000,0.061249,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,1.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
evaluating performance approximation mechanisms budget constraints,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,1.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
truthful reporting competence minimal verification,0.0,0.00000,0.000000,0.0,0.0,0.0,0.067873,0.000000,0.00000,0.0,0.000000,0.0,1.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
revenueoptimal pricing budgetconstrained buyers data markets,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,1.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000
personalization aids pluralistic alignment competition,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,1.000000,0.0,0.0,0.000000,0.000000,0.073652
complexity tournament fixing subset fas number acyclic neighborhoods,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,1.0,0.0,0.000000,0.000000,0.000000
majoritarian assignment rules,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.0,0.000000,0.000000,0.000000
ai arms influence frontier models exhibit sophisticated reasoning simulated nuclear crises,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,1.000000,0.047436,0.000000
governing ai forgetting auditing machine unlearning compliance,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.047436,1.000000,0.000000
sociallyweighted alignment gametheoretic framework multiagent llm systems,0.0,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.061039,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.073652,0.0,0.0,0.000000,0.000000,1.000000

In [374]:
cosine_df.iloc[8].sort_values(ascending=False)

offline learning nash stable coalition structures possibly overlapping coalitions             1.00000
distortion stable matching                                                                    0.08636
robust value maximization challenge champ tournaments probabilistic outcomes                  0.00000
evaluating performance approximation mechanisms budget constraints                            0.00000
governing ai forgetting auditing machine unlearning compliance                                0.00000
ai arms influence frontier models exhibit sophisticated reasoning simulated nuclear crises    0.00000
majoritarian assignment rules                                                                 0.00000
complexity tournament fixing subset fas number acyclic neighborhoods                          0.00000
personalization aids pluralistic alignment competition                                        0.00000
revenueoptimal pricing budgetconstrained buyers data markets                                  0.00000
truthful reporting competence minimal verification                                            0.00000
pareto bowley reinsurance games peertopeer insurance                                          0.00000
characterizing robustness strategies novelty zerosum open worlds                              0.00000
bayesian framework humanai collaboration complementarity correlation neglect                  0.00000
truthful reverse auctions adaptive selection contextual multiarmed bandits                    0.00000
nearoptimal bestofbothworlds fairness agents                                                  0.00000
revenue guarantees autobidding platforms                                                      0.00000
fair allocation initial utilities                                                             0.00000
thermal minmax games unifying bounded rationality typicalcase equilibrium                     0.00000
sociallyweighted alignment gametheoretic framework multiagent llm systems                     0.00000
Name: offline learning nash stable coalition structures possibly overlapping coalitions, dtype: float64

# Kmeans

In [379]:
from sklearn.cluster import KMeans

In [395]:
k = 4
kmeans = KMeans(
    n_clusters = k,
    random_state = 42,
    n_init = 20
)

kmeans.fit(tfidf_matrix)

KMeans(n_clusters=4, n_init=20, random_state=42)

In [397]:
labels = kmeans.labels_
cluster_df = pd.DataFrame({
    "title": titles,
    "cluster": labels
})

cluster_df

                                                title  cluster
0   robust value maximization challenge champ tour...        2
1                          distortion stable matching        3
2   thermal minmax games unifying bounded rational...        2
3                   fair allocation initial utilities        2
4            revenue guarantees autobidding platforms        2
5        nearoptimal bestofbothworlds fairness agents        2
6   truthful reverse auctions adaptive selection c...        0
7   bayesian framework humanai collaboration compl...        1
8   offline learning nash stable coalition structu...        3
9   characterizing robustness strategies novelty z...        2
10  pareto bowley reinsurance games peertopeer ins...        2
11  evaluating performance approximation mechanism...        2
12  truthful reporting competence minimal verifica...        0
13  revenueoptimal pricing budgetconstrained buyer...        2
14  personalization aids pluralistic alignment com...        1
15  complexity tournament fixing subset fas number...        2
16                      majoritarian assignment rules        2
17  ai arms influence frontier models exhibit soph...        2
18  governing ai forgetting auditing machine unlea...        2
19  sociallyweighted alignment gametheoretic frame...        1

## top term

In [404]:
import numpy as np
terms = tfidf_vec.get_feature_names_out()

for i in range(k):
    print(f"\nCluster {i}:")
    center = kmeans.cluster_centers_[i]
    top = center.argsort()[-10:][::-1]

    for idx in top:
        print(terms[idx])

Cluster 0:
truthful
truthful reporting
verification
reporting competence
reporting
competence minimal
competence
minimal verification
minimal
auctions

Cluster 1:
alignment
framework
competition
aids
pluralistic alignment
personalization
personalization aids
alignment competition
aids pluralistic
pluralistic

Cluster 2:
games
majoritarian assignment
assignment rules
assignment
rules
majoritarian
ai
guarantees
revenue
revenue guarantees

Cluster 3:
stable
distortion stable
stable matching
matching
distortion
offline learning
stable coalition
nash stable
offline
nash